# Site settings
title: allison m. vicenzi
email: allison@vicenzi.co
description: > # this means to ignore newlines until "baseurl:"
  love it or fix it. having fun exploring the garment industry, unexpected collaborations, the magic and vulnerability of bringing ideas to life. based in NYC and on the open road.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://allievice.com" # the base hostname & protocol for your site
twitter_username: allievice
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
